<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-NAVEEN" ignored="2" name="Default test(failed)" tests="4" failures="1" timestamp="07 Sep 2022 10:48:13 GMT" time="0.178" errors="0">
  <testcase name="tc2" time="0.012" classname="org.com.AutomaticallyKnownFailedTc">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.003" classname="org.com.AutomaticallyKnownFailedTc">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.002" classname="org.com.AutomaticallyKnownFailedTc">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase name="tc2" time="0.004" classname="org.com.AutomaticallyKnownFailedTc">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.com.AutomaticallyKnownFailedTc.tc2(AutomaticallyKnownFailedTc.java:13)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase name="tc1" time="0.0" classname="org.com.AutomaticallyKnownFailedTc">
    <ignored/>
  </testcase> <!-- tc1 -->
  <testcase name="tc3" time="0.0" classname="org.com.AutomaticallyKnownFailedTc">
    <ignored/>
  </testcase> <!-- tc3 -->
</testsuite> <!-- Default test(failed) -->
